### ISSUE TITLE
Last update of your plugin mapcycle have an error. 

### ISSUE THREAD

**Issue by veg88** [RonanLOUARN/Map-Cycle#4]
I used version  1.0.4 and works perfectly. But the last one have an error.
The error: 
2024-01-06 00:01:51.251 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MapCycle.MapCycle.ChangeMap() in C:\Users\Ronan\Desktop\cs_plugins\Map-Cycle\MapCycle.cs:line 217
   at InvokeStub_Action.Invoke(Object, Object, IntPtr)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>cDisplayClass3_0.<.ctor>b0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by RonanLOUARN** [comment]
I'll check that. Thanks for you report :)

**Comment by RonanLOUARN** [comment]
Fixed in the new release v1.1.1
[Here](https://github.com/RonanLOUARN/Map-Cycle/releases/tag/release-v-1.1.1)

**Comment by veg88** [comment]
Thx for being so fast. I donated 2 $.
